[package]
name = "tomasulo"
version = "0.1.0"
authors = ["MashPlant <740678788@qq.com>"]
edition = "2018"

[dependencies]
cursive = "*"
ranged = { git = "https://github.com/MashPlant/ranged" }

[lib]
path = "src/lib.rs"

[[bin]]
name = "tomasulo-tui"
path = "src/tui.rs"